name: Generate 3D Contribution Graph

on:
    # run automatically every day 00:00 UTC
    schedule:
        - cron: "0 0 * * *"

    # allows to run the job at any time manually
    workflow_dispatch:

    # run on every push on the main branch
    # push:
    #  branches:
    #   - main

jobs:
    build:
        name: Generate 3D Contribution Graph
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Generate 3D Contribution Graph
              uses: yoshi389111/github-profile-3d-contrib@0.7.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  USERNAME: ${{ github.repository_owner }}

            - name: Commit & Push
              run: |
                  git config user.name "Harsh Dobariya"
                  git config user.email harshdobariya2206@gmail.com
                  git add -A .
                  git commit -m "Generate 3D Contribution Graph"
                  git push
