name: Generate Snake Animation

on:
    # run automatically on the 1st day of each month at 00:00 UTC
    schedule:
        - cron: "0 0 1 * *"

    # allows manual trigger
    workflow_dispatch:

    # Uncomment if you want to run on every push on the main branch
    # push:
    #   branches:
    #     - main

permissions:
    contents: write # required for pushing to a branch

jobs:
    generate:
        name: Generate Snake Animation
        runs-on: ubuntu-latest
        steps:
            - name: Generate contribution_snake_grid.svg
              uses: Platane/snk@v3
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: |
                      dist/contribution_snake_grid.svg
                      dist/contribution_snake_grid_darkBlue.svg?palette=github-dark&color_snake=#3c7dd9

            - name: Push contribution_snake_grid.svg to the contribution branch
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: contribution
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
